version: '2'

services:
  ezbot:
    build:
      context: .
    container_name: EZcontainer
    image: ricker95/ezbot:version-latest
    env_file:
      - .env
    restart: always
    command: node dist/src/index.js
